---
title: "Appendix"
author: "Ossi Sirkka"
date: "8 12 2020"
output: html_document
---
# Appendix

## Appendix 1

```{r, appendix1, eval = TRUE}
tables_2007 <- lapply(vanha$data, table, exclude = TRUE)
tables_2018 <- lapply(uusi$data, table, exclude = TRUE)

tables_list <- lapply(seq_len(length(tables_2007)), function(i){
  
  if (all(which(c(length(tables_2007[[i]]), length(tables_2018[[i]])) == min(c(length(tables_2007[[i]]), length(tables_2018[[i]])))) == 1)){
    tables_2007[[i]][length(tables_2007[[i]]) + 1] <- NA
  } else if (all(which(c(length(tables_2007[[i]]), length(tables_2018[[i]])) == min(c(length(tables_2007[[i]]), length(tables_2018[[i]])))) == 2)){
  tables_2018[[i]][length(tables_2018[[i]]) + 1] <- NA
}
    
  
  data.frame(
    Variable = c(str_sub(names(tables_2007[[i]][1]), start = 1, end = nchar(names(tables_2007[[i]][1]))-1 ),
                 rep(" ", length(names(tables_2007[[i]]))-1)),
    Label = names(tables_2007[[i]]),
    Frequency_2007 = c(unname(tables_2007[[i]])),
    Frequency_2018 = c(unname(tables_2018[[i]])))
})

tables_df <- do.call(rbind, tables_list)
tables_df <- tables_df[!str_detect(tables_df$Label, "NA") & !is.na(tables_df$Label),]
tables_df <- add_column(tables_df,
                        Class = c(mod_luokitukset, rep(" ", nrow(tables_df) - length(mod_luokitukset))),
                        .before = "Frequency_2007")


create_kable(tables_df, otsikko = "Full list of indicators used to constuct identical spaces of lifestyles in 2007 and 2018 ")
```

## Appendix 2

```{r, appendix2, eval = TRUE}
new_vars_tables <- lapply(newdat$data[, which(names(newdat$data) == "Toimintapelit"):ncol(newdat$data[,!names(newdat$data) %in% sup.vars])], table, exclude = TRUE)
tables_new_list <- lapply(seq_len(length(new_vars_tables)), function(i){
  data.frame(
    Variable = c(str_sub(names(new_vars_tables[[i]][1]), start = 1, end = nchar(names(new_vars_tables[[i]][1]))-1 ),
                 rep(" ", length(names(new_vars_tables[[i]]))-1)),
    Label = names(new_vars_tables[[i]]),
    Frequency = c(unname(new_vars_tables[[i]])))
})

new_tables_df <- do.call(rbind, tables_new_list)
new_tables_df <- add_column(new_tables_df[str_detect(new_tables_df$Label, "NA", negate = TRUE),], Class = mod_luokitukset_uudet_muuttujat, .after = "Label")


create_kable(new_tables_df, otsikko = "List of additional indicators used to constuct comprehensive space of lifestyles with 2018 data")

```

## Appendix 3

```{r}

cat("\nSignificant changes in axis 1\n")
res_df_axis1 %>%
  mutate(pval_1 = as.numeric(pval_1)) %>% 
  arrange(pval_1) %>% 
  filter(pval_1 < 0.01)


cat("\nSignificant changes in axis 2\n")
res_df_axis2 %>%
  mutate(pval_2 = as.numeric(pval_2)) %>% 
  arrange(pval_2) %>% 
  filter(pval_2 < 0.01)


cat("\nSignificant changes in plane of axes 1 and 2\n")
res_df_plane %>%
  mutate(pval = as.numeric(pval)) %>% 
  arrange(pval) %>% 
  filter(pval < 0.01)

```

