---
title: "conclusions"
author: "Ossi Sirkka"
date: "8 12 2020"
output: html_document
bibliography: space-of-lifestyles.bib
csl: apa.csl
---


# Conclusions

  * Two dimensions are sufficient to represent space of lifestyles in Finland, both 2007 and 2018
    * Both dimensions remained quite stable during 11 year period
    * With identical set of indicators in 2007 and 2018, the explanatory power of traditional-modern axis declined, possible because of 1) cohort effect (most traditional age group got off the survey) and 2) no emerging indicators of contemporary lifestyle practices were included (e.g. gaming, online indicators), which leaded to underpresentation of cultural goods consumed by youngest age cohort, 18-24 year old young adults. This can be confirmed from Figure 3.7, where age group of 25-34 year old adults are as modern as 18-24 year old, which was not the case in 2007. Adding cultural good consumed by youngest population to the analysis, the youngest cohort became also the most modern. 
    * Considering individual items used to construct the space of lifestyles in 2007 and 2018, some cultural indicators experienced notable change in their location in the space. For example, reading at least some books turned from not being separating in neither axis in 2007 to being modern and legitimate practice.
  
  * Conducting MCA with comprehensive set of indicators revealed position of contemporary lifestyle practices in the space of lifestyles. From the indicators available in the survey but not yet included in first two steps of the analysis, majority were contributing more strongly in second, traditional-modern axis. 
  * Being involved in gaming were indicator of modern and slightly illegitimate lifestyle. Activities online and in social media were located also in modern side of the space, but more strongly in the legitimate side of the space. 
  
  
The analysis shows that two dimensions are sufficient to represent space of lifestyles in Finland, in both 2007 and 2018. Same dimensions remained the most important when we introduced new lifestyle indicators regarding both online and offline everyday activities, although the online indicators did increase the explanation power of second dimensions at the expense of first dimension. The emergence of these dimensions, legitimacy and modernity/traditionality of cultural practices, as the main structuring factors of the space of lifestyles, did not come as surprise; similar result was obtained by Purhonen et al. [-@purhonen_suomalainen_2014] in study of space of lifestyles in Finland in 2007, using the same data set as in this article.

Outside of Finland, similar results are found in the studies of lifestyles. Specifically the second structuring dimension, modernity-traditionality, have been found in numerous studies with similar research design [e.g @bennett_culture_2009; @roose_culture_2012; @coulangeon_changing_2013; @cveticanin_art_2011]. This dimension is has been interpreted with different labels, e.g.  "contemporary - established" ["@bennett_culture_2009], but the meaning is essentially the same. As it was shown in the analysis, this dimensions is mainly structured by age (with correlation coefficient -0.8). Clearly age is very important background variable when studying stratification of lifestyles. Our analysis also hints that average position of age cohort remained relatively stable from 2007 to 2018, which indicates that cultural tastes are linked to the cultural history of the generation individual comes from [@glevarec_structure_2020]. In other words, inter-cohort effects seem to play more significant role in the changing landscape in the cultural map than intra-cohort ones. 





