---
title: "introduction and theory"
author: "Ossi Sirkka"
date: "7 12 2020"
output:
  html_document: default
  word_document: default
bibliography: space-of-lifestyles.bib
csl: apa.csl
---

```{r tags, include = FALSE}
sort(bib2df::bib2df("space-of-lifestyles.bib")$BIBTEXKEY)
```

# Introduction / Theory

### Aim of this paper

In this article, we will examine the space of lifestyles in Finland in 2007 and 2018. Additionally, we will redo the analysis of 2018 with additional indicators relating to e.g. digital and mundane cultural practices. This allows us to answer to our two-fold research questions: 1) has the social structure in the space of lifestyles remained stable during 11-year period, and 2) what is the impact of additional, both modern and mundane, indicators, when they are added to the space of lifestyles? To answer these questions, we use comprehensive set of lifestyle indicators drawn from nationally representative data from Finland from the respective years. To analyze the data, we use Spesific Multiple Correspondence Analysis [@le_roux_multiple_2010], and elaborate our results with hierarchical clustering analysis of the SpeMCA-solutions.

Our analysis is three-fold. First, we simultaneously conduct two separate MCA-models for data from 2007 and 2018. After examining and comparing these models, we use 2007 model as a baseline model, and add observations from 2018 as supplementary individuals. This allows us to compare both locations of clouds of individuals and cultural items and examine the change. Then, we complement the model of 2018 with additional indicators related to digital and mundane practices, and examine space of lifestyles created with comprehensive set of indicators.   

The space of lifestyles visualizes cultural tastes and practices in a society in relation to each other. Individuals and their lifestyles can be mapped to the space in relations to other individuals and their lifestyles. This complex space of lifestyles can then be reduced to include two main structuring dimensions that separates different lifestyles. In the classical work of Pierre Bourdieu [-@bourdieu_distinction_1984], these dimensions were composition and amount of cultural and economic capital. With different approach to the analysis of lifestyles and social space, these dimensions have been legitimacy and modernity of cultural tastes and practices [e.g. @purhonen_suomalainen_2014]. Regardless of the approach, these spaces have been structured by the principle of homology [@bourdieu_distinction_1984], correspondence between social class and cultural preferences. Homology thesis is important starting point for examining cultural tastes and practices, as it assumes that individuals class position, habitus and lifestyles are intertwined [@weingartner_changing_2019]. Interesting question is, how this relationship shifts in time; is there any changes in the space of lifestyles and their relationship to social determinants in Finland, and if there are, is the change in the scale of main distinctive dimensions that separate lifestyles, or in locations of individual cultural indicators in the space of lifestyles? We hypothesize that

>$H_{1a}$: The main separating dimensios in the space of lifestyles has remained stable during eleven year period. Nevertheless, there has been changes in locations of individual cultural items.

Due to timely dimension in our study, distinguishing between intra- and intercohort effects in change [e.g. @putnam_bowling_2000] would be crucial to understand the change happened in space of lifestyles in Finland in 2007-2018. With our data, however, separating these different dynamics in change is very difficult, if not impossible. Some intercohort effect should be observable, however, and in any case more significant than intra-cohort changes in lifestyles (at least in the field of music, where tastes acquired during youth often persist in adulthood @donnat_les_2009; @glevarec_structure_2020). The oldest generation in 2007 was not included in the data of 2018, so we can expect that mean position of individuals in space of lifestyles in 2018 is less traditional than in 2007, due to exclusion of oldest and thus most traditional cohort of individuals. Similarly, we expect that lifestyle indicators favored by youngest cohort in 2007 are less separating in 2018. This stems from the fact that choice of included lifestyle indicators is limited by available variables in 2007 data, which means that no lifestyle indicators favored by youngest cohort of 2018 are present in the model. 

>$H_{2a}$: When comparing individuals of 2018 in space of 2007, due to inter-cohort effect, mean position of individuals in spafe of lifestyles in 2018 is less traditional compared to 2007. 

>$H_{2b}$: Most modern lifestyle indicators included in the analysis are less separating in 2018 than they were in 2007. 

The era in the scope of this article, 2007-2018, in Finland, is marked by rapid digitization of cultural consumption and production. Social media platforms such as Facebook, Instagram and Twitter have become increasingly important in the daily life, and cultural goods, such as music, is in theory easily accessible regardless of time and space. How this rapid change effects to the space of lifestyles, is however unclear, and will be a subject of examination in this article. Considering the two-dimensional representation of space of lifestyles, it is interesting to see the location of emerging digital practices, and social factors that are linked to them. We hypothesize that

>$H_{3a}$: Digital consumption is mainly related to younger - middle age individuals with higher amout of cultural capital, but some fringe forms of digital consumption are indicators of low cultural capital.

In previous research concerning space of lifestyles, some individuals have been found to have passive lifestyle, in a sense that they seem to not practice or like any of the lifestyle indicators included in the research, and this can be interpreted as passive lifestyle. We argue, however, that this passive cluster of individuals found in research in space of lifestyles, does not reflect real world, but rather the structure of surveys used to collect the data and their emphasis on narrow definition of culture. In the third step of our analysis, we will include more mundane, everyday practices such as playing card games or fishing in our analysis, and we expect that some of these practices are located in same locations in the space of lifestyles that are occupied by otherwise (in terms of narrow definition of culture) passive individuals.

>$H_{3b}$: Some mundane cultural practices such as foragin or hunting occupy locations in the space of lifestyles that are otherwise related to disliking and never-doing.

There are plentiful of studies focusing in the space of lifestyles in different national contexts conducted by Multiple Correspondence Analysis [e.g. @coulangeon_is_2007; @hjellbrekke_norwegian_2007; @bennett_culture_2009; and @roose_culture_2012]. Studies with temporal focus in space of lifestyles that utilize MCA are more scarce. Study conducted by Weingartner & Rössel [-@weingartner_changing_2019] examined changes in space of lifestyles happened in Switzerland 1976-2013, by conducting separate MCA-models for three different time points. With their analysis, they identify three different modes of cultural consumption, which are stable over time. They also found out that relationship between high socio-economic position and cultural consumption had shifted from highbrow activities to broad cultural engagement. Roselund [-@rosenlund_persistence_2019] compared populations of Norwegian urban area Stavanger from two different time points, 1994 and 2009 with methodologically similiar approach we do in this article. By constructing cultural map that had main dimensions of volume and composition of capital, his main results were that during time, citizens had become richer in both cultural and economic forms of capital and differentiating power of capital composition had increased. At the same time a shift in space of lifestyles towards more culturally and politically inclined practices were observed (selvennä...)


