---
title: 'The space of lifestyles in Finland, 2007 and 2018: Continuity and change'
author: "Ossi Sirkka, Semi Purhonen"
date: '`r format(Sys.Date(), "%d. %B %Y")`'
abstract: "Have the ways in which cultural practices are socially structured changed over the last 10–15 years, a period marked by digitization of cultural consumption and production and increased socio-political polarization? This work-in-progress paper tackles this question by analyzing two repeated nationally representative surveys, collected in Finland in 2007 (N=1,388) and 2018 (N=1,425), allowing comparisons over time and including a wide set of indicators of cultural practices. Applying multiple correspondence analysis (MCA), the paper sets out to construct the space of lifestyles – or, “cultural map” – in Finland in both 2007 and 2018. The analysis carried out, inspired by the few studies having used MCA in analyzing temporal changes, includes three steps. First, the space of lifestyles for 2007 is constructed using more than 100 indicators of cultural practices, while the socio-political divisions are projected onto the space as supplementary variables. Second, the space of lifestyles for 2018 is constructed using exactly identical set of indicators as for 2007 to investigate the nature of changes, if measured symmetrically. Third, to reveal the impact of new cultural practices that were not available for the 2007 data, the space of lifestyles for 2018 is constructed again, this time using also a comprehensive set of additional indicators of social media and other online and offline everyday activities. The results are discussed in the light of other recent research focusing on the temporal dynamics of cultural stratification in different national contexts."
keywords: "Cultural practices, space of lifestyles, taste, stratification, change, multiple correspondence analysis"
output: 
  bookdown::html_document2:
  number_sections: TRUE
  fig_caption: TRUE
  pdf_document:
    toc: TRUE
bibliography: space-of-lifestyles.bib
csl: apa.csl
---

```{r BIBTEXTAGS, include = FALSE}
sort(bib2df::bib2df("space-of-lifestyles.bib")$BIBTEXKEY)
```

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=14, fig.height=14,
                      dev = "png",
                      fig.path=paste0(getwd(),'/images_for_article/'),
                      echo=FALSE, warning=FALSE, message=FALSE)



```

```{r, child = "models_and_data.Rmd"}
```

```{r, child = "introduction_theory.Rmd"}
```

```{r, child = "research_desing.Rmd"}
```

```{r, child = "analysis.Rmd"}
```

```{r, child = "conclusions.Rmd"}
```
 
```{r, child = "appendix.Rmd"}
```

# References