#' @title DATASET_TITLE
#' @description DATASET_DESCRIPTION
#' @format A data frame with 14182 rows and 114 variables:
#' \describe{
#'   \item{\code{af}}{character COLUMN_DESCRIPTION}
#'   \item{\code{sq}}{character COLUMN_DESCRIPTION}
#'   \item{\code{am}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ar}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hy}}{character COLUMN_DESCRIPTION}
#'   \item{\code{az}}{character COLUMN_DESCRIPTION}
#'   \item{\code{eu}}{character COLUMN_DESCRIPTION}
#'   \item{\code{be}}{character COLUMN_DESCRIPTION}
#'   \item{\code{bn}}{character COLUMN_DESCRIPTION}
#'   \item{\code{bs}}{character COLUMN_DESCRIPTION}
#'   \item{\code{bg}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ca}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ceb}}{character COLUMN_DESCRIPTION}
#'   \item{\code{zh-CN}}{character COLUMN_DESCRIPTION}
#'   \item{\code{zh-TW}}{character COLUMN_DESCRIPTION}
#'   \item{\code{co}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hr}}{character COLUMN_DESCRIPTION}
#'   \item{\code{cs}}{character COLUMN_DESCRIPTION}
#'   \item{\code{da}}{character COLUMN_DESCRIPTION}
#'   \item{\code{nl}}{character COLUMN_DESCRIPTION}
#'   \item{\code{en...22}}{character COLUMN_DESCRIPTION}
#'   \item{\code{eo}}{character COLUMN_DESCRIPTION}
#'   \item{\code{et}}{character COLUMN_DESCRIPTION}
#'   \item{\code{fi}}{character COLUMN_DESCRIPTION}
#'   \item{\code{fr}}{character COLUMN_DESCRIPTION}
#'   \item{\code{fy}}{character COLUMN_DESCRIPTION}
#'   \item{\code{gl}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ka}}{character COLUMN_DESCRIPTION}
#'   \item{\code{de}}{character COLUMN_DESCRIPTION}
#'   \item{\code{el}}{character COLUMN_DESCRIPTION}
#'   \item{\code{gu}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ht}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ha}}{character COLUMN_DESCRIPTION}
#'   \item{\code{haw}}{character COLUMN_DESCRIPTION}
#'   \item{\code{iw}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hi}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hmn}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hu}}{character COLUMN_DESCRIPTION}
#'   \item{\code{is}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ig}}{character COLUMN_DESCRIPTION}
#'   \item{\code{id}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ga}}{character COLUMN_DESCRIPTION}
#'   \item{\code{it}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ja}}{character COLUMN_DESCRIPTION}
#'   \item{\code{jw}}{character COLUMN_DESCRIPTION}
#'   \item{\code{kn}}{character COLUMN_DESCRIPTION}
#'   \item{\code{kk}}{character COLUMN_DESCRIPTION}
#'   \item{\code{km}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ko}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ku}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ky}}{character COLUMN_DESCRIPTION}
#'   \item{\code{lo}}{character COLUMN_DESCRIPTION}
#'   \item{\code{la}}{character COLUMN_DESCRIPTION}
#'   \item{\code{lv}}{character COLUMN_DESCRIPTION}
#'   \item{\code{lt}}{character COLUMN_DESCRIPTION}
#'   \item{\code{lb}}{character COLUMN_DESCRIPTION}
#'   \item{\code{mk}}{character COLUMN_DESCRIPTION}
#'   \item{\code{mg}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ms}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ml}}{character COLUMN_DESCRIPTION}
#'   \item{\code{mt}}{character COLUMN_DESCRIPTION}
#'   \item{\code{mi}}{character COLUMN_DESCRIPTION}
#'   \item{\code{mr}}{character COLUMN_DESCRIPTION}
#'   \item{\code{mn}}{character COLUMN_DESCRIPTION}
#'   \item{\code{my}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ne}}{character COLUMN_DESCRIPTION}
#'   \item{\code{no}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ny}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ps}}{character COLUMN_DESCRIPTION}
#'   \item{\code{fa}}{character COLUMN_DESCRIPTION}
#'   \item{\code{pl}}{character COLUMN_DESCRIPTION}
#'   \item{\code{pt}}{character COLUMN_DESCRIPTION}
#'   \item{\code{pa}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ro}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ru}}{character COLUMN_DESCRIPTION}
#'   \item{\code{sm}}{character COLUMN_DESCRIPTION}
#'   \item{\code{gd}}{character COLUMN_DESCRIPTION}
#'   \item{\code{sr}}{character COLUMN_DESCRIPTION}
#'   \item{\code{st}}{character COLUMN_DESCRIPTION}
#'   \item{\code{sn}}{character COLUMN_DESCRIPTION}
#'   \item{\code{sd}}{character COLUMN_DESCRIPTION}
#'   \item{\code{si}}{character COLUMN_DESCRIPTION}
#'   \item{\code{sk}}{character COLUMN_DESCRIPTION}
#'   \item{\code{sl}}{character COLUMN_DESCRIPTION}
#'   \item{\code{so}}{character COLUMN_DESCRIPTION}
#'   \item{\code{es}}{character COLUMN_DESCRIPTION}
#'   \item{\code{su}}{character COLUMN_DESCRIPTION}
#'   \item{\code{sw}}{character COLUMN_DESCRIPTION}
#'   \item{\code{sv}}{character COLUMN_DESCRIPTION}
#'   \item{\code{tl}}{character COLUMN_DESCRIPTION}
#'   \item{\code{tg}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ta}}{character COLUMN_DESCRIPTION}
#'   \item{\code{te}}{character COLUMN_DESCRIPTION}
#'   \item{\code{th}}{character COLUMN_DESCRIPTION}
#'   \item{\code{tr}}{character COLUMN_DESCRIPTION}
#'   \item{\code{uk}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ur}}{character COLUMN_DESCRIPTION}
#'   \item{\code{uz}}{character COLUMN_DESCRIPTION}
#'   \item{\code{vi}}{character COLUMN_DESCRIPTION}
#'   \item{\code{cy}}{character COLUMN_DESCRIPTION}
#'   \item{\code{xh}}{character COLUMN_DESCRIPTION}
#'   \item{\code{yi}}{character COLUMN_DESCRIPTION}
#'   \item{\code{yo}}{character COLUMN_DESCRIPTION}
#'   \item{\code{zu}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Positive}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Negative}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Anger}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Anticipation}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Disgust}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Fear}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Joy}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Sadness}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Surprise}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Trust}}{double COLUMN_DESCRIPTION}
#'}
#' @source \url{http://somewhere.important.com/}
"NRC_Emotion_Lexicon"
